### ISSUE TITLE
Config is read twice

### ISSUE THREAD

**Issue by urosgruber** [DoubleCheck/log-ship-elastic-postfix#14]
Because of 

`var cfg       = config.loadConfig();`

in postifx doc loadConfig gets called twice, the first time from /etc and the second time from current folder.

How do you feel about using node-config module instead?

**Comment by msimerson** [comment]
Nah.  If you are worried about loading a tiny config file twice (it's in the kernels filesystem cache, it's cheap!), then I'd choose to instead export a function such that when `require('config')` is called, you get the same thing as currently calling `require('config').loadConfig();`, which takes advantage of nodes [built-in module caching](https://nodejs.org/api/modules.html#modules_module_caching_caveats). And then you don't need another dependency.

**Comment by urosgruber** [comment]
I was not worried about performance but because I copy the file to /etc make a change and then try to use it, but it was still reading from the config in log-ship-elastic-postfix folder. Result is pretty mixed up

´´´
Reading configuration from /etc/log-ship-elastic-postfix.ini
---------------------------------------
TZ: Australia/Sydney
logship....
Reading configuration from /Users/uros/Sites/node_modules/log-ship-elastic-postfix/log-ship-elastic-postfix.ini
---------------------------------------
parent dir: /var/spool_local/log_ship
´´´

So as you see TZ is ready from /etc location but the spool path from local node_modules folder.

**Comment by msimerson** [comment]
I see the problem now. Please have a look at #15 and tell me if that addresses your issue fully.
