### ISSUE TITLE
unable to parse logs

### ISSUE THREAD

**Issue by etfeet** [DoubleCheck/log-ship-elastic-postfix#7]
I'm having a little trouble getting this working.

I'm getting the following error:

bookmark.read: line 542
end of /var/log/maillog
bookmark.save: line: 542
doQueue: empty
watching /var/log/maillog
bookmark.read: line 542
        bytes.start: 73621
        skipped 542 lines
end of /var/log/maillog
bookmark.save: line: 552
doQueue: 10 lines
watching /var/log/maillog
        elastic doc matches: 0
        updatePfDocs: new: 2

{ [Error: Request Timeout after 30000ms] status: '408', message: 'Request Timeout after 30000ms' }

/var/log/maillog:

Sep 24 15:02:07 localhost postfix/pickup[23088]: 84BD9106F4F: uid=0 from=<root>
Sep 24 15:02:07 localhost postfix/cleanup[23932]: 84BD9106F4F: message-id=<20150924220207.84BD9106F4F@localhost.localdomain>
Sep 24 15:02:07 localhost postfix/qmgr[3552]: 84BD9106F4F: from=<root@localhost.localdomain>, size=278, nrcpt=1 (queue active)
Sep 24 15:02:07 localhost postfix/local[23933]: 84BD9106F4F: to=<root@localhost.localdomain>, orig_to=<root@localhost>, relay=local, delay=0.04, delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 24 15:02:07 localhost postfix/qmgr[3552]: 84BD9106F4F: removed

logstash.stdout:

                 "message" => "Sep 24 15:02:07 localhost postfix/pickup[23088]: 84BD9106F4F: uid=0 from=<root>",
                "@version" => "1",
              "@timestamp" => "2015-09-24T22:02:07.000Z",
                    "type" => "postfix",
                    "file" => "/var/log/maillog",
                    "host" => "localhost.localdomain",
                  "offset" => "77930",
        "syslog_timestamp" => "Sep 24 15:02:07",
         "syslog_hostname" => "localhost",
          "syslog_program" => "postfix/pickup",
              "syslog_pid" => "23088",
          "syslog_message" => "84BD9106F4F: uid=0 from=<root>",
             "received_at" => "2015-09-24T22:02:14.883Z",
           "received_from" => "localhost.localdomain",
    "syslog_severity_code" => 5,
    "syslog_facility_code" => 1,
         "syslog_facility" => "user-level",
         "syslog_severity" => "notice"
}
{
                 "message" => "Sep 24 15:02:07 localhost postfix/cleanup[23932]: 84BD9106F4F: message-id=<20150924220207.84BD9106F4F@localhost.localdomain>",
                "@version" => "1",
              "@timestamp" => "2015-09-24T22:02:07.000Z",
                    "type" => "postfix",
                    "file" => "/var/log/maillog",
                    "host" => "localhost.localdomain",
                  "offset" => "78010",
        "syslog_timestamp" => "Sep 24 15:02:07",
         "syslog_hostname" => "localhost",
          "syslog_program" => "postfix/cleanup",
              "syslog_pid" => "23932",
          "syslog_message" => "84BD9106F4F: message-id=<20150924220207.84BD9106F4F@localhost.localdomain>",
             "received_at" => "2015-09-24T22:02:14.884Z",
           "received_from" => "localhost.localdomain",
    "syslog_severity_code" => 5,
    "syslog_facility_code" => 1,
         "syslog_facility" => "user-level",
         "syslog_severity" => "notice"
}
{
                 "message" => "Sep 24 15:02:07 localhost postfix/qmgr[3552]: 84BD9106F4F: from=<root@localhost.localdomain>, size=278, nrcpt=1 (queue active)",
                "@version" => "1",
              "@timestamp" => "2015-09-24T22:02:07.000Z",
                    "type" => "postfix",
                    "file" => "/var/log/maillog",
                    "host" => "localhost.localdomain",
                  "offset" => "78135",
        "syslog_timestamp" => "Sep 24 15:02:07",
         "syslog_hostname" => "localhost",
          "syslog_program" => "postfix/qmgr",
              "syslog_pid" => "3552",
          "syslog_message" => "84BD9106F4F: from=<root@localhost.localdomain>, size=278, nrcpt=1 (queue active)",
             "received_at" => "2015-09-24T22:02:14.895Z",
           "received_from" => "localhost.localdomain",
    "syslog_severity_code" => 5,
    "syslog_facility_code" => 1,
         "syslog_facility" => "user-level",
         "syslog_severity" => "notice"
}
{
                 "message" => "Sep 24 15:02:07 localhost postfix/local[23933]: 84BD9106F4F: to=<root@localhost.localdomain>, orig_to=<root@localhost>, relay=local, delay=0.04, delays                                                       =0.02/0.01/0/0, dsn=2.0.0, status=sent (delivered to mailbox)",
                "@version" => "1",
              "@timestamp" => "2015-09-24T22:02:07.000Z",
                    "type" => "postfix",
                    "file" => "/var/log/maillog",
                    "host" => "localhost.localdomain",
                  "offset" => "78262",
        "syslog_timestamp" => "Sep 24 15:02:07",
         "syslog_hostname" => "localhost",
          "syslog_program" => "postfix/local",
              "syslog_pid" => "23933",
          "syslog_message" => "84BD9106F4F: to=<root@localhost.localdomain>, orig_to=<root@localhost>, relay=local, delay=0.04, delays=0.02/0.01/0/0, dsn=2.0.0, status=sent (delivere                                                       d to mailbox)",
             "received_at" => "2015-09-24T22:02:14.896Z",
           "received_from" => "localhost.localdomain",
    "syslog_severity_code" => 5,
    "syslog_facility_code" => 1,
         "syslog_facility" => "user-level",
         "syslog_severity" => "notice"
}
{
                 "message" => "Sep 24 15:02:07 localhost postfix/qmgr[3552]: 84BD9106F4F: removed",
                "@version" => "1",
              "@timestamp" => "2015-09-24T22:02:07.000Z",
                    "type" => "postfix",
                    "file" => "/var/log/maillog",
                    "host" => "localhost.localdomain",
                  "offset" => "78475",
        "syslog_timestamp" => "Sep 24 15:02:07",
         "syslog_hostname" => "localhost",
          "syslog_program" => "postfix/qmgr",
              "syslog_pid" => "3552",
          "syslog_message" => "84BD9106F4F: removed",
             "received_at" => "2015-09-24T22:02:14.897Z",
           "received_from" => "localhost.localdomain",
    "syslog_severity_code" => 5,
    "syslog_facility_code" => 1,
         "syslog_facility" => "user-level",
         "syslog_severity" => "notice"
}

logstash config stuff:

    grok {
      type => "postfix"
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }

if [type] == "postfix" {
  elasticsearch {
        host => "localhost"
        index => "postfix-orphan-%{+YYYY-MM-dd}"
        #template_name => "postfix-orphan"
        template => "/etc/logstash/index-map-template.json"
        }
  stdout { codec => rubydebug }
}

log ship config file:

[main]
spool=/var/spool/log_ship/postfix
;email=admin@example.com

[elastic]
module=elasticsearch
hosts=localhost:9200
index=postfix-orphan-2015-09-24
type=postfix
batch=1024
batchDelay=5

[parser]
module=postfix-parser

; syslog lines don't have time zone data. Do set this!
; timezone map: http://momentjs.com/timezone/
timezone=America/Los_Angeles

[reader]
module=safe-log-reader
file=/var/log/maillog

; how many seconds after a log file has grown to resume reading
watchDelay=10

any help would be appreciated,

Rory

**Comment by msimerson** [comment]
````
bookmark.read: line 542
end of /var/log/maillog
bookmark.save: line: 542
doQueue: empty
watching /var/log/maillog
bookmark.read: line 542
bytes.start: 73621
skipped 542 lines
end of /var/log/maillog
bookmark.save: line: 552
doQueue: 10 lines
watching /var/log/maillog
elastic doc matches: 0
updatePfDocs: new: 2
````

That's all good status messages. The problem appears to be here:

````
{ [Error: Request Timeout after 30000ms] status: '408', message: 'Request Timeout after 30000ms' }
````

It looks like Elasticsearch didn't respond within 30 seconds. Figure out why and fix that and you should be good to go.

**Comment by etfeet** [comment]
okay I was able to fix the problems with elasticsearch. However, it doesn't seem to be matching the from field correctly.

maillog shows:

Sep 25 12:07:55 rory-dev postfix/pickup[1625]: ED373F8043E: uid=1000 from=<rory>
Sep 25 12:07:55 rory-dev postfix/cleanup[13246]: ED373F8043E: message-id=<20150925190755.ED373F8043E@rory-dev.localdomain>
Sep 25 12:07:56 rory-dev postfix/qmgr[1626]: ED373F8043E: from=<rory@rory-dev.localdomain>, size=270, nrcpt=1 (queue active)
Sep 25 12:07:56 rory-dev postfix/local[13248]: ED373F8043E: to=<root@localhost.localdomain>, orig_to=<root@localhost>, relay=local, delay=0.11, delays=0.07/0/0/0.04, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 25 12:07:56 rory-dev postfix/qmgr[1626]: ED373F8043E: removed

and this is what shows up in es


{
"_index": "postfix-orphan-2015-09-25",
"_type": "postfix-orphan",
"_id": "ED373F8043E",
"_version": 1,
"_score": null,
"_source": {
"host": "rory-dev",
"events": [
{
"date": "2015-09-25T12:07:56-07:00",
"action": "queued"
}
,
{
"to": "root@localhost.localdomain",
"orig_to": "root@localhost",
"relay": "local",
"delay": "0.11",
"delays": "0.07/0/0/0.04",
"dsn": "2.0.0",
"status": "sent (delivered to mailbox)",
"date": "2015-09-25T12:07:56-07:00"
}
],
"date": "2015-09-25T12:07:55-07:00",
"isFinal": false,
"uid": "1000",
"message-id": "20150925190755.ED373F8043E@rory-dev.localdomain",
"from": ""
},
"sort": [
1443208075000
]
}


which has an empty from field but the log shows from=<rory@rory-dev.localdomain>.

Also how do I get this to match against existing es docs?

Thanks!,

Rory

**Comment by msimerson** [comment]
It wasn't matching from because in your logs, there's no angle brackets in the email addresses. I have updated the parser so that angle brackets are optional, which should resolve that problem.

As to matching against ES docs, that all depends on how you had them structured **before**. That's an exercise left to you and whatever existing ES docs you want to match against.
